services:
  - type: web
    runtime: docker
    name: documenso-browserless
    plan: starter
    dockerfilePath: ./Dockerfile.browserless
    healthCheckPath: /
    envVars:
      - key: CONCURRENT
        value: 10
      - key: TOKEN
        generateValue: true
      - key: MAX_CONCURRENT_SESSIONS
        value: 10
      - key: PREBOOT_CHROME
        value: true

  - type: web
    runtime: node
    name: documenso-app
    plan: free
    buildCommand: npm i && npm run build
    startCommand: npx prisma migrate deploy --schema packages/prisma/schema.prisma && npx turbo run start @documenso/remix
    healthCheckPath: /api/health

    envVars:
      # Node Version
      - key: NODE_VERSION
        value: 22.16.0

      - key: PORT
        value: 3000

      # Auth
      - key: NEXTAUTH_URL
        fromService:
          name: documenso-app
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXTAUTH_SECRET
        generateValue: true

      - key: NEXT_PRIVATE_BROWSERLESS_URL
        fromService:
          name: documenso-browserless
          type: web
          envVarKey: RENDER_EXTERNAL_URL

      # Database
      - key: NEXT_PRIVATE_DATABASE_URL
        fromDatabase:
          name: documenso-db
          property: connectionString

      - key: NEXT_PRIVATE_DIRECT_DATABASE_URL
        fromDatabase:
          name: documenso-db
          property: connectionString

      # URLs
      - key: NEXT_PUBLIC_WEBAPP_URL
        fromService:
          name: documenso-app
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: NEXT_PRIVATE_INTERNAL_WEBAPP_URL
        value: 'http://localhost:3000'

      # SMTP
      - key: NEXT_PRIVATE_SMTP_TRANSPORT
        sync: false
      - key: NEXT_PRIVATE_SMTP_HOST
        sync: false
      - key: NEXT_PRIVATE_SMTP_PORT
        sync: false
      - key: NEXT_PRIVATE_SMTP_USERNAME
        sync: false
      - key: NEXT_PRIVATE_SMTP_PASSWORD
        sync: false
      - key: NEXT_PRIVATE_SMTP_FROM_NAME
        sync: false
      - key: NEXT_PRIVATE_SMTP_FROM_ADDRESS
        sync: false

      # Storage
      - key: NEXT_PUBLIC_UPLOAD_TRANSPORT
        sync: false
      - key: NEXT_PRIVATE_UPLOAD_FORCE_PATH_STYLE
        sync: false
      - key: NEXT_PRIVATE_UPLOAD_REGION
        sync: false
      - key: NEXT_PRIVATE_UPLOAD_BUCKET
        sync: false
      - key: NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID
        sync: false
      - key: NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY
        sync: false

      # Crypto
      - key: NEXT_PRIVATE_ENCRYPTION_KEY
        generateValue: true
      - key: NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY
        generateValue: true

      # Signing
      - key: NEXT_PRIVATE_SIGNING_TRANSPORT
        sync: false
      - key: NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH
        sync: false
      - key: NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS
        sync: false

      # SMTP Optional
      - key: NEXT_PRIVATE_RESEND_API_KEY
        sync: false
      - key: NEXT_PUBLIC_DOCUMENT_SIZE_UPLOAD_LIMIT
        sync: false

      # Features Optional
      - key: NEXT_PUBLIC_DISABLE_SIGNUP
        sync: false
